# -*- coding: utf-8 -*-
"""location.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ejlFgSthxSXcHRAx-W3sB9HSQIXtlDJL
"""

import requests
import json
URL = "https://geocode.search.hereapi.com/v1/geocode"
location = input("Enter the location here: ") 

__api_key='jmfj1sE9OLUa7I2893mzr91bVCfybMNjkH9Pb_JHdy4'
PARAMS = {'apikey':api_key,'q':location} 

r = requests.get(url = URL, params = PARAMS) 
data = r.json()

latitude = data['items'][0]['position']['lat']
longitude = data['items'][0]['position']['lng']
print(latitude, longitude)