# -*- coding: utf-8 -*-
"""search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a-N30iRHNBY6jhSBAuS8116mbtbuEnuV
"""

try:
    from googlesearch import search
except ImportError: 
    print("No module named 'google' found")
  
site = input('Hello, What you want to search?')
  
for i in search(site, tld="co.in", num=10, stop=10, pause=2):
    print(i)